#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

files_to_fix = [
    'landing-servicos.html',
    'inspecao-playgrounds.html',
    'inspecao-pressurizacao-escadas.html',
    'inspecao-sistemas-mecanicos.html',
    'inspecao-hvac-pmoc.html',
    'inspecao-gas-predial.html',
    'goiania/inspecao-predial-goiania.html',
    'rio-verde/inspecao-predial-rio-verde.html',
    'teste-arrancamento-olhais.html',
    'laudo-pericial-engenharia.html',
    'inspecao-combate-incendio.html',
    'inspecao-casa-bombas.html',
    'analise-vibracao-elevadores.html',
    'cercon-goias.html',
    'franquias.html',
    'anapolis/inspecao-predial-anapolis.html',
    'brasilia/inspecao-predial-brasilia.html',
    'conhecimento-tecnico/index.html',
]

replacements = {
    'tàcnico': 'técnico', 'tàcnica': 'técnica', 'Tàcnico': 'Técnico', 'Tàcnica': 'Técnica',
        'TàCNICAS': 'TÉCNICAS',
    'sàndico': 'síndico', 'sàndicos': 'síndicos', 'Sàndico': 'Síndico', 'Sàndicos': 'Síndicos',
    'edifàcio': 'edifício', 'edifàcios': 'edifícios', 'Edifàcio': 'Edifício', 'Edifàcios': 'Edifícios',
    'condomànio': 'condomínio', 'condomànios': 'condomínios', 'Condomànio': 'Condomínio',
    'condàminos': 'condôminos', 'Condàminos': 'Condôminos',
    'àrea': 'área', 'àreas': 'áreas', 'Àrea': 'Área', 'Àreas': 'Áreas',
    'goiània': 'goiânia', 'Goiània': 'Goiânia', 'anàpolis': 'anápolis', 'Anàpolis': 'Anápolis',
    'brasàlia': 'brasília', 'Brasàlia': 'Brasília',
    'responsàvel': 'responsável', 'responsàveis': 'responsáveis',
    'peràcia': 'perícia', 'Peràcia': 'Perícia',
    'balanão': 'balanço', 'seguranàa': 'segurança', 'expàe': 'expõe', 'tàm': 'têm',
    'proprietàrio': 'proprietário', 'Proprietàrio': 'Proprietário',
    'juàzo': 'juízo', 'Juàzo': 'Juízo', 'justiàa': 'justiça', 'Justiàa': 'Justiça',
    'critàrios': 'critérios', 'Critàrios': 'Critérios',
    'aplicàvel': 'aplicável', 'subsàdios': 'subsídios',
    'conclusàes': 'conclusões', 'Conclusàes': 'Conclusões',
    'càmaras': 'câmaras', 'especàficos': 'específicos', 'favoreàam': 'favoreçam',
    'cientàfico': 'científico', 'cientàfica': 'científica', 'Cientàfico': 'Científico',
    'curràculo': 'currículo', 'Curràculo': 'Currículo',
    'nàmero': 'número', 'Nàmero': 'Número',
    'goiàs': 'goiás', 'Goiàs': 'Goiás',
    'Mecànica': 'Mecânica', 'mecànica': 'mecânica',
    'vàcio': 'vício', 'vàcios': 'vícios', 'Vàcio': 'Vício', 'Vàcios': 'Vícios',
    'compatàveis': 'compatíveis', 'compatàvel': 'compatível',
    'visàvel': 'visível', 'visàveis': 'visíveis', 'Visàvel': 'Visível',
    'làngua': 'língua', 'ilegàvel': 'ilegível',
    'percebidos': 'percebidos', 'indàcios': 'indícios', 'fàsicos': 'físicos', 'fàsicas': 'físicas',
    'ambàguas': 'ambíguas', 'ambàgua': 'ambígua',
    'especàficos': 'específicos', 'Especàficos': 'Específicos',
    'inàcio': 'início', 'Inàcio': 'Início',
    'equilàbrio': 'equilíbrio', 'Equilàbrio': 'Equilíbrio',
    'contànua': 'contínua', 'Contànua': 'Contínua',
    'resàduos': 'resíduos', 'Resàduos': 'Resíduos',
    'eletroeletrônicos': 'eletroeletrônicos',
    'mànimo': 'mínimo', 'màsimo': 'máximo', 'periàdica': 'periódica',
    'baixàssima': 'baixíssima', 'Baixàssima': 'Baixíssima',
    'Indàstrias': 'Indústrias', 'indàstrias': 'indústrias',
    'Galpàes': 'Galpões', 'galpàes': 'galpões',
    'exaustào': 'exaustão', 'Exaustào': 'Exaustão',
    'Serviàos': 'Serviços', 'serviàos': 'serviços',
    'serviào': 'serviço', 'Serviào': 'Serviço',
    'Hotàis': 'Hotéis', 'hotàis': 'hotéis',
    'clànicas': 'clínicas', 'Clànicas': 'Clínicas',
    'ginàsios': 'ginásios', 'Ginàsios': 'Ginásios',
    'caracteràsticas': 'características', 'Caracteràsticas': 'Características',
    'especàficas': 'específicas', 'Especàficas': 'Específicas',
    'quàmicos': 'químicos', 'Quàmicos': 'Químicos',
    'atravàs': 'através', 'Atravàs': 'Através',
    'aào': 'aço', 'Aào': 'Aço',
    'sintàtica': 'sintética', 'Sintàtica': 'Sintética',
    'extensàes': 'extensões', 'Extensàes': 'Extensões',
    'intermediàrios': 'intermediários', 'Intermediàrios': 'Intermediários',
    'Chaminàs': 'Chaminés', 'chaminàs': 'chaminés',
    'Disponàveis': 'Disponíveis', 'disponàveis': 'disponíveis',
    'ràgido': 'rígido', 'ràgida': 'rígida', 'Ràgido': 'Rígido', 'Ràgida': 'Rígida',
    'Alumànio': 'Alumínio', 'alumànio': 'alumínio',
    'Tripà': 'Tripé', 'tripà': 'tripé',
    'espaàos': 'espaços', 'Espaàos': 'Espaços',
    'espaào': 'espaço', 'Espaào': 'Espaço',
    'màquinas': 'máquinas', 'Màquinas': 'Máquinas',
    'conexàes': 'conexões', 'Conexàes': 'Conexões',
    'Estàtica': 'Estética', 'estàtica': 'estética',
    'hà': 'há', 'Hà': 'Há',
    'Màveis': 'Móveis', 'màveis': 'móveis',
    'temporàrios': 'temporários', 'Temporàrios': 'Temporários',
    'transportàveis': 'transportáveis', 'Transportàveis': 'Transportáveis',
    'metàlicas': 'metálicas', 'Metàlicas': 'Metálicas',
    'superfàcies': 'superfícies', 'Superfàcies': 'Superfícies',
    'tambàm': 'também', 'Tambàm': 'Também',
    'suportarào': 'suportarão', 'Suportarào': 'Suportarão',
    'Ministàrio': 'Ministério', 'ministàrio': 'ministério',
    'Anàlise': 'Análise', 'anàlise': 'análise',
    'Aptidào': 'Aptidão', 'aptidào': 'aptidão',
    'màdica': 'médica', 'Màdica': 'Médica',
    'especàfica': 'específica', 'Especàfica': 'Específica',
    'màxima': 'máxima', 'Màxima': 'Máxima',
    'Foràas': 'Forças', 'foràas': 'forças',
    'referància': 'referência', 'Referància': 'Referência',
    'negligància': 'negligência', 'Negligància': 'Negligência',
    'saàde': 'saúde', 'Saàde': 'Saúde',
    'CONSEQUàNCIAS': 'CONSEQUÊNCIAS', 'Consequàncias': 'Consequências', 'consequàncias': 'consequências',
    'ausància': 'ausência', 'Ausància': 'Ausência',
    'sàrias': 'sérias', 'Sàrias': 'Sérias',
    'Observatério': 'Observatório', 'observatério': 'observatório',
    'famàlia': 'família', 'Famàlia': 'Família',
    'polàticos': 'políticos', 'Polàticos': 'Políticos',
    "d'àgua": "d'água", "D'àgua": "D'água",
    'àgua': 'água', 'Àgua': 'Água',
    'Vàlvula': 'Válvula', 'vàlvula': 'válvula',
    'frequància': 'frequência', 'Frequància': 'Frequência',
    'reservatàrio': 'reservatório', 'Reservatàrio': 'Reservatório',
    'elàtricos': 'elétricos', 'Elàtricos': 'Elétricos',
    'elàtrica': 'elétrica', 'Elàtrica': 'Elétrica',
    'incàndio': 'incêndio', 'Incàndio': 'Incêndio',
    'intocàvel': 'intocável', 'Intocàvel': 'Intocável',
    'emergància': 'emergência', 'Emergància': 'Emergência',
    'obstruàdo': 'obstruído', 'Obstruàdo': 'Obstruído',
    'obstruàda': 'obstruída', 'Obstruàda': 'Obstruída',
    'NàO': 'NÃO',
    'càv': 'cav',
    'làt': 'lát',
    'gàn': 'gân',
    'uàn': 'uên',
    'iào': 'ião',
    'tàr': 'tár',
    'càn': 'cên',
    'uàd': 'uád',
    'à6à': '§6º', 'à3à': '§3º', 'à2à': '§2º', 'à1à': '§1º',
    'disponàvel': 'disponível', 'Disponàvel': 'Disponível',
    'Experiància': 'Experiência', 'experiància': 'experiência',
    'quàmicas': 'químicas', 'Quàmicas': 'Químicas',
    'padrào': 'padrão', 'Padrào': 'Padrão',
    'ràu': 'rau',
    'Distàncias': 'Distâncias', 'distàncias': 'distâncias',
    'higiànico': 'higiênico', 'Higiànico': 'Higiênico',
    'pràdio': 'prédio', 'Pràdio': 'Prédio',
    'exercàcio': 'exercício', 'Exercàcio': 'Exercício',
    'catastràfica': 'catastrófica', 'Catastràfica': 'Catastrófica',
    'irrefutàveis': 'irrefutáveis', 'Irrefutàveis': 'Irrefutáveis',
    'logàsticos': 'logísticos', 'Logàsticos': 'Logísticos',
    'càlculos': 'cálculos', 'Càlculos': 'Cálculos',
    'Càlculo': 'Cálculo', 'càlculo': 'cálculo',
    'Jataà': 'Jataí', 'jataà': 'jataí',
    'pràticas': 'práticas', 'Pràticas': 'Práticas',
    'Resistància': 'Resistência', 'resistància': 'resistência',
    'automàtica': 'automática', 'Automàtica': 'Automática',
    'desconfortàvel': 'desconfortável', 'Desconfortàvel': 'Desconfortável',
    'Legionàrio': 'Legionário', 'legionàrio': 'legionário',
    'Mànimo': 'Mínimo', 'mànimo': 'mínimo',
    'Combustào': 'Combustão', 'combustào': 'combustão',
    'denàncias': 'denúncias', 'Denàncias': 'Denúncias',
    'diagnàsticos': 'diagnósticos', 'Diagnàsticos': 'Diagnósticos',
    'Diària': 'Diária', 'diària': 'diária',
    'Energàtica': 'Energética', 'energàtica': 'energética',
    'Fàruns': 'Fóruns', 'fàruns': 'fóruns',
    'formulàrio': 'formulário', 'Formulàrio': 'Formulário',
    'nàa': 'nea',
    'ràa': 'rá',
    'Dàv': 'Dúv',
    'tàv': 'táv',
    'ràl': 'ral',
    'nàr': 'nár',
    'màt': 'mát',
    'Gàs': 'Gás', 'gàs': 'gás',
    'vàdeo': 'vídeo', 'Vàdeo': 'Vídeo', 'vàdeos': 'vídeos', 'Vàdeos': 'Vídeos',
    'atà': 'até', 'Atà': 'Até',
    'fumaàa': 'fumaça', 'Fumaàa': 'Fumaça',
    'Cràtica': 'Crítica', 'cràtica': 'crítica', 'cràticos': 'críticos', 'Cràticos': 'Críticos',
    'eficiància': 'eficiência', 'Eficiància': 'Eficiência',
    'Càdigo': 'Código', 'càdigo': 'código',
    'Fotogràfico': 'Fotográfico', 'fotogràfico': 'fotográfico',
    'àteis': 'úteis', 'Àteis': 'Úteis',
    'màdicos': 'médicos', 'Màdicos': 'Médicos',
    'Tàpicas': 'Típicas', 'tàpicas': 'típicas',
    'possàvel': 'possível', 'Possàvel': 'Possível',
    'mànimas': 'mínimas', 'Mànimas': 'Mínimas',
    'àtil': 'útil', 'Àtil': 'Útil',
    'Olà': 'Olá', 'olà': 'olá',
    'diagnàstico': 'diagnóstico', 'Diagnàstico': 'Diagnóstico',
    'microbiolàgica': 'microbiológica', 'Microbiolàgica': 'Microbiológica',
    'vocà': 'você', 'Vocà': 'Você',
    'Apàs': 'Após', 'apàs': 'após',
    'cabeàa': 'cabeça', 'Cabeàa': 'Cabeça',
    'Màdio': 'Médio', 'màdio': 'médio',
    'Vigilància': 'Vigilância', 'vigilància': 'vigilância',
    'peàas': 'peças', 'Peàas': 'Peças',
    'frigoràficas': 'frigoríficas', 'Frigoràficas': 'Frigoríficas',
    'serà': 'será', 'Serà': 'Será',
    '360à': '360°',
    'especàfico': 'específico', 'Especàfico': 'Específico',
    'confiàvel': 'confiável', 'Confiàvel': 'Confiável',
    'Denància': 'Denúncia', 'denància': 'denúncia',
    'pràvia': 'prévia', 'Pràvia': 'Prévia',
    'periàdico': 'periódico', 'Periàdico': 'Periódico',
    'pràximo': 'próximo', 'Pràximo': 'Próximo',
    'notàcia': 'notícia', 'Notàcia': 'Notícia',
    'simultàneo': 'simultâneo', 'Simultàneo': 'Simultâneo',
    'diàmetro': 'diâmetro', 'Diàmetro': 'Diâmetro',
    'Superintendància': 'Superintendência', 'superintendància': 'superintendência',
    'Reincidància': 'Reincidência', 'reincidància': 'reincidência',
    'vitalàcia': 'vitalícia', 'Vitalàcia': 'Vitalícia',
    'CONDàMINOS': 'CONDÔMINOS', 'condàmino': 'condômino', 'Condàmino': 'Condômino',
    'pagarà': 'pagará', 'Pagarà': 'Pagará',
    'PRàTICO': 'PRÁTICO', 'pràtico': 'prático', 'Pràtico': 'Prático',
    'acessàvel': 'acessível', 'Acessàvel': 'Acessível',
    'juràdica': 'jurídica', 'Juràdica': 'Jurídica',
    'àltimo': 'último', 'Àltimo': 'Último',
    'antecedància': 'antecedência', 'Antecedància': 'Antecedência',
    'desagradàveis': 'desagradáveis', 'Desagradàveis': 'Desagradáveis',
    'tragàdia': 'tragédia', 'Tragàdia': 'Tragédia',
}

total_fixed = 0
total_replacements = 0

for file_path in files_to_fix:
    if not os.path.exists(file_path):
        print(f"⚠️  {file_path} não encontrado")
        continue
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        file_replacements = 0
        
        for old, new in replacements.items():
            count = content.count(old)
            if count > 0:
                content = content.replace(old, new)
                file_replacements += count
        
        if content != original:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✅ {file_path:<50} {file_replacements} correções")
            total_fixed += 1
            total_replacements += file_replacements
        else:
            print(f"✓  {file_path:<50} OK")
            
    except Exception as e:
        print(f"❌ {file_path}: {e}")

print(f"\n✅ {total_fixed} arquivos corrigidos - {total_replacements} substituições")
